/**
 * Derives the web image set from the campaign photography.
 *
 * One master photograph per reference lives in assets/campaign/. Every framing
 * is a crop of that frame, so the whole collection stays one session — which is
 * how it was shot. Nothing is re-posed here.
 *
 * The casebacks in assets/caseback/ are the exception: the back of the watch is
 * the same part on every reference, so it is shot once and derived once into
 * _shared/ rather than copied into all five product folders. A caseback whose
 * source file is missing is reported and skipped, never faked.
 */
import { mkdirSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { COLLECTIONS } from "../src/lib/catalog/millenium";
import {
  SHARED_SHOTS,
  SHOTS,
  shotHeight,
  type ShotSpec,
} from "../src/lib/catalog/shots";

const ROOT = process.cwd();
const OUT = join(ROOT, "public", "products");
const SRC = join(ROOT, "assets", "campaign");
const SHARED_SRC = join(ROOT, "assets", "caseback");

/** Finds the master file for a product, whatever extension it carries. */
function master(slug: string) {
  for (const ext of ["png", "webp", "jpg", "jpeg"]) {
    const p = join(SRC, `${slug}.${ext}`);
    if (existsSync(p)) return p;
  }
  throw new Error(`no campaign master for "${slug}" in assets/campaign/`);
}

/** Finds a shared source by basename, whatever extension it carries. */
function sharedSource(name: string) {
  for (const ext of ["png", "webp", "jpg", "jpeg"]) {
    const p = join(SHARED_SRC, `${name}.${ext}`);
    if (existsSync(p)) return p;
  }
  return null;
}

function cropBox(srcW: number, srcH: number, s: ShotSpec) {
  const w = Math.round(srcW * s.scale);
  const h = Math.round(w / s.ratio);
  // Clamp so a crop can never run past the edge of the master.
  const maxH = Math.min(h, srcH);
  const maxW = Math.min(w, srcW);
  const left = Math.max(0, Math.min(srcW - maxW, Math.round(srcW * s.centre.x - maxW / 2)));
  const top = Math.max(0, Math.min(srcH - maxH, Math.round(srcH * s.centre.y - maxH / 2)));
  return { left, top, width: maxW, height: maxH };
}

async function main() {
  const blur: Record<string, string> = {};

  for (const collection of COLLECTIONS) {
    for (const product of collection.products) {
      const src = master(product.slug);
      const meta = await sharp(src).metadata();
      const dir = join(OUT, collection.slug, product.slug);
      mkdirSync(dir, { recursive: true });

      for (const s of SHOTS) {
        const box = cropBox(meta.width!, meta.height!, s);
        const pipeline = sharp(src)
          .extract(box)
          .resize(s.w, shotHeight(s), { fit: "cover", kernel: "lanczos3" });

        await pipeline
          .clone()
          .webp({ quality: 84, effort: 6 })
          .toFile(join(dir, `${s.role}.webp`));

        const lqip = await pipeline
          .clone()
          .resize(16, null, { fit: "inside" })
          .blur(1.1)
          .webp({ quality: 28 })
          .toBuffer();
        blur[`${collection.slug}/${product.slug}/${s.role}`] =
          `data:image/webp;base64,${lqip.toString("base64")}`;

        process.stdout.write(`  ${collection.slug}/${product.slug}/${s.role}\n`);
      }
    }

    // Shared framings: derived once per collection, not once per reference.
    for (const s of SHARED_SHOTS) {
      const src = sharedSource(s.source);
      if (!src) {
        process.stdout.write(
          `  skipped ${collection.slug}/_shared/${s.role} — no assets/caseback/${s.source}.*\n`
        );
        continue;
      }
      const dir = join(OUT, collection.slug, "_shared");
      mkdirSync(dir, { recursive: true });

      const h = Math.round(s.w / s.ratio);
      const pipeline = sharp(src).resize(s.w, h, { fit: "cover", kernel: "lanczos3" });

      await pipeline
        .clone()
        .webp({ quality: 84, effort: 6 })
        .toFile(join(dir, `${s.role}.webp`));

      const lqip = await pipeline
        .clone()
        .resize(16, null, { fit: "inside" })
        .blur(1.1)
        .webp({ quality: 28 })
        .toBuffer();
      blur[`${collection.slug}/_shared/${s.role}`] =
        `data:image/webp;base64,${lqip.toString("base64")}`;

      process.stdout.write(`  ${collection.slug}/_shared/${s.role}\n`);
    }
  }

  const lines = Object.entries(blur)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");
  writeFileSync(
    join(ROOT, "src", "lib", "catalog", "blur.generated.ts"),
    `// Generated by scripts/build-assets.mts. Do not edit by hand.\n` +
      `/** Low-quality inline previews, keyed by "<collection>/<product>/<role>". */\n` +
      `export const BLUR: Record<string, string> = {\n${lines}\n};\n`
  );
  console.log("campaign derived from assets/campaign/");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
