// Generated by scripts/build-assets.mts. Do not edit by hand.
/** Low-quality inline previews, keyed by "<collection>/<product>/<role>". */
export const BLUR: Record<string, string> = {
  "millenium/onyx/hero": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoQABQAPxl2tFGspyUisAgBkCMJZwDCgCHQQIC9eGrJhbpwAP6qW5j1XmiIVqoxHGxU5SpefqoSzfv4XAiGtTT2hMziJlR26gMtKlpMAAA=",
  "millenium/onyx/angle": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoQABQAPxl2s1EspySisAgBkCMJaQAAUz/ZzNrvVH6Jm2awAAD+5NATRDywzpuSNu8HDd9SQz4quK4b6apDk6ZEL3TKJOQY9gBAAA==",
  "millenium/onyx/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPxl2slCspySisAgBkCMJZwDCgB59YSklAqe6XsfoAP69jNPUfTWaqBsWLKvJi45Txnzh58AoOlIqJA3LSxhoBBt8NMJYX4+2mMAAAA==",
  "millenium/onyx/card": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoQABQAPxl2slCspySisAgBkCMJZwDCgCHw/HgAvty8A4m6PTAA/ttIqG3UwPQU4vZoS1iqprLViEtKyRP91ox+fkyyH4hEKISPUf1wAAA=",
  "millenium/lagoon/hero": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoQABQAPxl2slCspySisAgBkCMJZQCw7B582Gy1+uVO+AD+1erI8U15QC9IaK2GzVJz7ynUah2ToNDQGgiHYzgijBw0YWmP/tUT8ZfJ6yHoIyEAAAA=",
  "millenium/lagoon/angle": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZQCdAB58228rzfLXG2AA+Op2HjtRYZ5OkLhWoNZpVQFjfel2VD+aRId1KEYHGnXnBQYoRHUnwVizkAA=",
  "millenium/lagoon/lifestyle": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoQABQAPxl4slEspySisAgBkCMJZQCdABSjY/o2+skza/aAAAD8ivNRGnGXb9e3Fq3D8aNJwJg6J+BodNODb+KGLDe5zB7Iwl0feSzbco9zussHkPAAAA==",
  "millenium/lagoon/card": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoQABQAPxl2s1EspySisAgBkCMJZQCsABuw6nl8aII+11BsiwAA/l/eczxtBhL5gAgG8MRRdX4rzbf4l/H3YUQ8yBespgGqeaj4hEjZA7pMSK3UZwAAAA==",
  "millenium/chrome/hero": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZwDE2BtdWRqoXHQYBgAA/sjlplr8TrKufKtTJChfayVfrugjoU/qB2of1uxqIyJ7xuV+VIPpU3xmIAA=",
  "millenium/chrome/angle": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoQABQAPxl2s1EspySisAgBkCMJZQC+SB0/cgMYwlCXy513AAD97NfkX9eKcwrwOgsr0zGeRhYiC1IHPrTQ35zlx+HWq3Cfo6MHeZeuxXjVRntwAAA=",
  "millenium/chrome/lifestyle": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZwAAO0LYEP7eVNEP7dwA4fugjubI85eqThFJ2RbJj58sSZ92OHKIL/PRtU7DB9+4/Qa/tcCMwdMgIAA=",
  "millenium/chrome/card": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoQABQAPxl4slEspySisAgBkCMJZQDCgB50rp6TeZ2T+Y4+QAD+lMj5so44TTpvWJD8pOzcOzuwAALlrP5y2bqE2b6RSJTc74w11lcxPezPxQAA",
  "millenium/blush/hero": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoQABQAPxl4s1EspySisAgBkCMJZwCw7BtddKgSpDValOgA/rQOWGxtzaJWH8zMCzAnuC47hYXt2aSyhp2KbaCPfy9sTLnvqSCacjchmAi+/AAA",
  "millenium/blush/angle": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwBACdASoQABQAPxl2slCspySisAgBkCMJZQCsBagBTUmrkdmAKu4ebsd0NAD7qXjVvRI5JPQvrpUHzdDAoUuwsFPbrUYzl/TGi4I+eKl6cAAA",
  "millenium/blush/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoQABQAPxl0sVCspqSisAgBkCMJZQDCgBuMrcjGYI5rVqPRHkAAyxU41Sq6R2Vn9mJ1hZF4gWBK9pkg23Ctv5/mrVFPOv6lgJesUbDlpeb8AA==",
  "millenium/blush/card": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABQAPxl4s1EspySisAgBkCMJZQCsABuwo2pz72bitfFAAPj70/xRzImrQhaSkz+xZuZ5aFGtN0tkN3l3k8z5wLft0Yn2d/MikCATz0+rX/8mjXkAAA==",
  "millenium/solaris/hero": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAwCdASoQABQAPxl2s1CspySisAgBkCMJZwAASFX8PAxcHaAA/mFQEm/6g5TxyLoYm2r2Pdiv6GdX096/3n80xmB5v/SR0zxMNVgtEsU+1ZgauevPj7e1QAA=",
  "millenium/solaris/angle": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQBACdASoQABQAPxl4s1CspySisAgBkCMJZQDG9BuJ9zLrMhZQrzjT+eQAAP1ztxog0gk59hLCbWiXUxayyQUJmoMqBYPhHYZuXKP/SR2QpagZLcpf/oxgAAA=",
  "millenium/solaris/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPxl4slCspySisAgBkCMJZQCw7BttIFl5TjylSl1gAPubgJH5op7hXQGj+lGwmPuMPOOyEpo69WbA7BD1PQ2tohNgUMucGPm+2q8AAA==",
  "millenium/solaris/card": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoQABQAPxl2slCspySisAgBkCMJZwCzgBttIJG9R/vWAM4usvSg4L4ro+UrZkq5e6ned5eOxYKgOgsDs11acUW1ubry06bAfwOwkXZI3MR5uHRDAAA=",
};
