// Generated by scripts/build-assets.mts. Do not edit by hand.
/** Low-quality inline previews, keyed by "<collection>/<product>/<role>". */
export const BLUR: Record<string, string> = {
  "millenium/onyx/hero": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoQABQAPxl2tFGspyUisAgBkCMJZwDCgCHQQIC9eGrJhbpwAP6qW5j1XmiIVqoxHGxU5SpefqoSzfv4XAiGtTT2hMziJlR26gMtKlpMAAA=",
  "millenium/onyx/angle": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoQABQAPxl2s1EspySisAgBkCMJaQAAUz/ZzNrvVH6Jm2awAAD+5NATRDywzpuSNu8HDd9SQz4quK4b6apDk6ZEL3TKJOQY9gBAAA==",
  "millenium/onyx/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPxl2slCspySisAgBkCMJZwDCgB59YSklAqe6XsfoAP69jNPUfTWaqBsWLKvJi45Txnzh58AoOlIqJA3LSxhoBBt8NMJYX4+2mMAAAA==",
  "millenium/onyx/card": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoQABQAPxl2slCspySisAgBkCMJZwDCgCHw/HgAvty8A4m6PTAA/ttIqG3UwPQU4vZoS1iqprLViEtKyRP91ox+fkyyH4hEKISPUf1wAAA=",
  "millenium/lagoon/hero": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoQABQAPxl2slCspySisAgBkCMJZQCw7B582Gy1+uVO+AD+1erI8U15QC9IaK2GzVJz7ynUah2ToNDQGgiHYzgijBw0YWmP/tUT8ZfJ6yHoIyEAAAA=",
  "millenium/lagoon/angle": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZQCdAB58228rzfLXG2AA+Op2HjtRYZ5OkLhWoNZpVQFjfel2VD+aRId1KEYHGnXnBQYoRHUnwVizkAA=",
  "millenium/lagoon/lifestyle": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoQABQAPxl4slEspySisAgBkCMJZQCdABSjY/o2+skza/aAAAD8ivNRGnGXb9e3Fq3D8aNJwJg6J+BodNODb+KGLDe5zB7Iwl0feSzbco9zussHkPAAAA==",
  "millenium/lagoon/card": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoQABQAPxl2s1EspySisAgBkCMJZQCsABuw6nl8aII+11BsiwAA/l/eczxtBhL5gAgG8MRRdX4rzbf4l/H3YUQ8yBespgGqeaj4hEjZA7pMSK3UZwAAAA==",
  "millenium/chrome/hero": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZwDE2BtdWRqoXHQYBgAA/sjlplr8TrKufKtTJChfayVfrugjoU/qB2of1uxqIyJ7xuV+VIPpU3xmIAA=",
  "millenium/chrome/angle": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoQABQAPxl2s1EspySisAgBkCMJZQC+SB0/cgMYwlCXy513AAD97NfkX9eKcwrwOgsr0zGeRhYiC1IHPrTQ35zlx+HWq3Cfo6MHeZeuxXjVRntwAAA=",
  "millenium/chrome/lifestyle": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZwAAO0LYEP7eVNEP7dwA4fugjubI85eqThFJ2RbJj58sSZ92OHKIL/PRtU7DB9+4/Qa/tcCMwdMgIAA=",
  "millenium/chrome/card": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoQABQAPxl4slEspySisAgBkCMJZQDCgB50rp6TeZ2T+Y4+QAD+lMj5so44TTpvWJD8pOzcOzuwAALlrP5y2bqE2b6RSJTc74w11lcxPezPxQAA",
  "millenium/blush/hero": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoQABQAPxl2slCspySisAgBkCMJZwAAMkSuWze2ja7xJwAA/u6MTEWRVjxP0RNtFaYUxO6ncBlTlqUWCTFPlXHzV7+DBiC8hy7xcAAA",
  "millenium/blush/angle": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoQABQAPxl0sVCspqSisAgBkCMJZQDDNBmthPYHtTuoAP7ByC0STsnwxBs/e7HN1dgTtTmekphfIa6974XmxSg9oU3Y5vO187OxDENvj+JzfkAA",
  "millenium/blush/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoQABQAPxl2slCspySisAgBkCMJZwDE2Bg9LqLiG54twAD+5oULjv+ItveILUv6WM9hZM0mM62JJRf0LKTCGPXMTxuc6SGMxPcgMi/KQeAAAA==",
  "millenium/blush/card": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoQABQAPxl2slEspySisAgBkCMJZQDCgBgckj+OTXS7dMAA/uaQRMZ5oZg8gBRGgty2MxcKvjpQ/m8x5OFfFVWby24jp+qDtmjqcHf+AAA=",
  "millenium/solaris/hero": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoQABQAPxl2s1EspySisAgBkCMJZwCw7B6CS4I/0/ewGAAA/sXfHwyUFkzWaoT0XX0KGCVaQcp0y0TvoHtdioVm/9ICGZMt5MpN02qsQoqFiQAA",
  "millenium/solaris/angle": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoQABQAPxl2slCspySisAgBkCMJZQCsAB59W753sD9gyg4AAPZMuVkm2w/uSF9gHZgLdPbhOeLuMPDQWs6W1v5pkhM0+gCe8vckHQEuDFCAPgAA",
  "millenium/solaris/lifestyle": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoQABQAPxl2s1CspySisAgBkCMJZQCw7BSrj2jEFhcYvrmgAM3YEPxsz0Fium5gQvkuIusq9WsKTTBrRfc7LTNjY2BhGv5l44/7RAQMWMKoagAA",
  "millenium/solaris/card": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoQABQAPxl2tFGspyUisAgBkCMJZQCxDHACd0zQ0A68H7ft6AAA/N+KcPfzlYfdV7oLSymEhCE3s5kzklx5c42NRqsm/jV1EL9vu86YjSZxo28VmptI4AAA",
};
