// Generated by scripts/build-assets.mts. Do not edit by hand.
/** Low-quality inline previews, keyed by "<collection>/<product>/<role>". */
export const BLUR: Record<string, string> = {
  "millenium/onyx/hero": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoQABQAPxl2tFGspyUisAgBkCMJZwDCgCHQQIC9eGrJhbpwAP6qW5j1XmiIVqoxHGxU5SpefqoSzfv4XAiGtTT2hMziJlR26gMtKlpMAAA=",
  "millenium/onyx/angle": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoQABQAPxl2s1EspySisAgBkCMJaQAAUz/ZzNrvVH6Jm2awAAD+5NATRDywzpuSNu8HDd9SQz4quK4b6apDk6ZEL3TKJOQY9gBAAA==",
  "millenium/onyx/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPxl2slCspySisAgBkCMJZwDCgB59YSklAqe6XsfoAP69jNPUfTWaqBsWLKvJi45Txnzh58AoOlIqJA3LSxhoBBt8NMJYX4+2mMAAAA==",
  "millenium/onyx/card": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoQABQAPxl2slCspySisAgBkCMJZwDCgCHw/HgAvty8A4m6PTAA/ttIqG3UwPQU4vZoS1iqprLViEtKyRP91ox+fkyyH4hEKISPUf1wAAA=",
  "millenium/lagoon/hero": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoQABQAPxl2slCspySisAgBkCMJYwCdABttI0oLeowQ/2l1cAD+tCTFLJa3JZV7tnmAItKM5YxTyqbvF8ZMHPnuGIfZqpdNxsuu3Kd7y2gW/wcAAAA=",
  "millenium/lagoon/angle": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoQABQAPxl0sVCspqSisAgBkCMJQBOgA22RVdQAGHQXXxAA+6kB1mGW3X8XNAjQtUQBsbTTyLwKiFXwG7LsU3mBGg78PDw40GwlXSOBKW7bTJIAAAA=",
  "millenium/lagoon/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQBACdASoQABQAPxl2s1EspySisAgBkCMJQBdgA29LNFDtR6P34Y8AAAD6jrYNXFM1U2Odfhl/xPYxq3rwATshDsNfPFJzzIcIESTJ5UoQdiqiwHgAAA==",
  "millenium/lagoon/card": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABQAPxl4slEspySisAgBkCMJQBOgA8+rSBMy96SG0ggAAOJtLFjeEEMsMPane4qIbXZhDg/ITDlM+JP5NhbopvXEX3mTFr4COhroQ+wZMF127QAAAA==",
  "millenium/chrome/hero": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABQAPxl4slEspySisAgBkCMJZwCw7BuMrb9TsTXxRsocAP60JMUsmTwmDKxIGr+kcdTCIbrvHDMnFqmGdJBaX/t/Q/yYz/PInMJ9c++IDCGlUU6lAAAA",
  "millenium/chrome/angle": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoQABQAPxl4slEspySisAgBkCMJZQCw7Bu16MU+0sfDoaJlAAD+QaUsupJDJwqc60MQeEMLbYnkG1YTeUAPbR4veyuwhigvL2bAR7RvXUyHEiAA",
  "millenium/chrome/lifestyle": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoQABQAPxl0sVCspqSisAgBkCMJZQCw7Btt7htaMa+B/AAA+o62IcN7rgs5TrAkDZOoAgHfqAbnVh9u2SAS8Hty++Upemoue0N3XPkXTi2PyjwRi1oskngA",
  "millenium/chrome/card": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABQAPxl2slCspySisAgBkCMJYwCw7Btt7pqAJrSpyhNAAM4wXKgwlzedBOHkWEtNB4jMy7jlZmFjMX5/b671MEMlhJj/L70hBODe7EX2dgm7tBaaqAAA",
  "millenium/blush/hero": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoQABQAPxl4s1EspySisAgBkCMJZwCw7BtddKgSpDValOgA/rQOWGxtzaJWH8zMCzAnuC47hYXt2aSyhp2KbaCPfy9sTLnvqSCacjchmAi+/AAA",
  "millenium/blush/angle": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwBACdASoQABQAPxl2slCspySisAgBkCMJZQCsBagBTUmrkdmAKu4ebsd0NAD7qXjVvRI5JPQvrpUHzdDAoUuwsFPbrUYzl/TGi4I+eKl6cAAA",
  "millenium/blush/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwBACdASoQABQAPxl0sVCspqSisAgBkCMJZQDCgBuMrcjGYI5rVqPRHkAAyxU41Sq6R2Vn9mJ1hZF4gWBK9pkg23Ctv5/mrVFPOv6lgJesUbDlpeb8AA==",
  "millenium/blush/card": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABQAPxl4s1EspySisAgBkCMJZQCsABuwo2pz72bitfFAAPj70/xRzImrQhaSkz+xZuZ5aFGtN0tkN3l3k8z5wLft0Yn2d/MikCATz0+rX/8mjXkAAA==",
  "millenium/solaris/hero": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAwCdASoQABQAPxl2s1CspySisAgBkCMJZwAASFX8PAxcHaAA/mFQEm/6g5TxyLoYm2r2Pdiv6GdX096/3n80xmB5v/SR0zxMNVgtEsU+1ZgauevPj7e1QAA=",
  "millenium/solaris/angle": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQBACdASoQABQAPxl4s1CspySisAgBkCMJZQDG9BuJ9zLrMhZQrzjT+eQAAP1ztxog0gk59hLCbWiXUxayyQUJmoMqBYPhHYZuXKP/SR2QpagZLcpf/oxgAAA=",
  "millenium/solaris/lifestyle": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPxl4slCspySisAgBkCMJZQCw7BttIFl5TjylSl1gAPubgJH5op7hXQGj+lGwmPuMPOOyEpo69WbA7BD1PQ2tohNgUMucGPm+2q8AAA==",
  "millenium/solaris/card": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoQABQAPxl2slCspySisAgBkCMJZwCzgBttIJG9R/vWAM4usvSg4L4ro+UrZkq5e6ned5eOxYKgOgsDs11acUW1ubry06bAfwOwkXZI3MR5uHRDAAA=",
};
