// Generated by scripts/build-assets.mts. Do not edit by hand.
/** Framings shared by every reference, discovered from assets/caseback/. */
export interface SharedImage {
  role: string;
  label: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const SHARED_IMAGES: SharedImage[] = [];
